# Create the geography lookup table for swadlr
#
# Run this script to regenerate R/sysdata.rda:
#   Rscript data-raw/geography-lookup.R

# National
national <- data.frame(
  id = "national",
  level = "national",

  name = "United States",
  abbr = "US",
  stringsAsFactors = FALSE
)

# Regions (4)
regions <- data.frame(
  id = c("regionMidwest", "regionNortheast", "regionSouth", "regionWest"),
  level = "region",
  name = c("Midwest", "Northeast", "South", "West"),
  abbr = NA_character_,
  stringsAsFactors = FALSE
)

# Census Divisions (9)
divisions <- data.frame(
  id = c(
    "division01",
    "division02",
    "division03",
    "division04",
    "division05",
    "division06",
    "division07",
    "division08",
    "division09"
  ),
  level = "division",
  name = c(
    "New England",
    "Middle Atlantic",
    "East North Central",
    "West North Central",
    "South Atlantic",
    "East South Central",
    "West South Central",
    "Mountain",
    "Pacific"
  ),
  abbr = NA_character_,
  stringsAsFactors = FALSE
)

# States + DC (51)
# FIPS codes: https://www.census.gov/library/reference/code-lists/ansi.html
states <- data.frame(
  id = c(
    "state01",
    "state02",
    "state04",
    "state05",
    "state06",
    "state08",
    "state09",
    "state10",
    "state11",
    "state12",
    "state13",
    "state15",
    "state16",
    "state17",
    "state18",
    "state19",
    "state20",
    "state21",
    "state22",
    "state23",
    "state24",
    "state25",
    "state26",
    "state27",
    "state28",
    "state29",
    "state30",
    "state31",
    "state32",
    "state33",
    "state34",
    "state35",
    "state36",
    "state37",
    "state38",
    "state39",
    "state40",
    "state41",
    "state42",
    "state44",
    "state45",
    "state46",
    "state47",
    "state48",
    "state49",
    "state50",
    "state51",
    "state53",
    "state54",
    "state55",
    "state56"
  ),
  level = "state",
  name = c(
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "District of Columbia",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming"
  ),
  abbr = c(
    "AL",
    "AK",
    "AZ",
    "AR",
    "CA",
    "CO",
    "CT",
    "DE",
    "DC",
    "FL",
    "GA",
    "HI",
    "ID",
    "IL",
    "IN",
    "IA",
    "KS",
    "KY",
    "LA",
    "ME",
    "MD",
    "MA",
    "MI",
    "MN",
    "MS",
    "MO",
    "MT",
    "NE",
    "NV",
    "NH",
    "NJ",
    "NM",
    "NY",
    "NC",
    "ND",
    "OH",
    "OK",
    "OR",
    "PA",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VT",
    "VA",
    "WA",
    "WV",
    "WI",
    "WY"
  ),
  stringsAsFactors = FALSE
)

# Combine all geographies
swadlr_geography_lookup <- rbind(national, regions, divisions, states)

# Save as internal data
usethis::use_data(swadlr_geography_lookup, internal = TRUE, overwrite = TRUE)
